### ISSUE TITLE
overwriting existing metadata - incorrect version compare

### ISSUE THREAD

**Issue by rdc-cbd** [kuleuven/mango-mdschema#2]
in schema.py (around line 90)

> #report if data is annotated with a previous version
>         existing_mdschema = avu_version_name in item.metadata
>         if existing_mdschema and item.metadata[avu_version_name] != self.version:
>             logging.warning(
>                 "There is existing metadata linked to a previous version of this schema. It will be removed."
>             )

The comparison item.metadata[avu_version_name] != self.version doesn't work since item.metadata[avu_version_name] returns an object with attribute name, value and unit.

Code should be changed to:

> # report if data is annotated with a previous version
>         existing_mdschema = avu_version_name in item.metadata
>         if existing_mdschema and item.metadata[avu_version_name]**value** != self.version:
>             logging.warning(
>                 "There is existing metadata linked to a previous version of this schema. It will be removed."
>             )

tested and confirmed working

**Comment by rmoreas** [comment]
Hi @rdc-cbd, thanks for reporting.
I'm currently working on this package. I will include your fix in the new release.

**Comment by rmoreas** [comment]
This has been resolved in the latest release
